### ISSUE TITLE
windows 11 cant find any shortcut and files after installed

### ISSUE THREAD

**Issue by xtay573269555** [MolotovCherry/virtual-display-rs#17]
Hi, I cannot find any file named including "Virtual Display" in my windows 11 after installed the software. I run `install-cert.bat` and then run `virtual-display-driver-0.2.5-x86_64.msi` with admin privileges.

It seems that it did not installed successfully.

```
OS name: Microsoft Windows 11 64bit
OS version:  10.0.22621  Build 22621
```

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/5844466/f1b23e8c-97cd-409b-b111-63dde5602b48)

**Comment by MolotovCherry** [comment]
- Did you see any errors during installation?
- What do you see in device manager?
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/8431fc9f-852c-4f42-a2c0-15113810017d)
- Is there anything at `C:\Program Files\VirtualDisplayDriver`?

**Comment by xtay573269555** [comment]
1. No error during installation.

2. There are 3 virtual display adapters because i installed the driver for 3 times.
<img width="535" alt="2023-10-11_09-10-47" src="https://github.com/MolotovCherry/virtual-display-rs/assets/5844466/2e753b1e-975a-41b4-82f0-637f9d9a9a06">

3. The path `C:\Program Files\VirtualDisplayDriver` does not exist.

4. No shortcut or folder named or related to Virtual Display Driver.

5. There is no any shortcut or file named "Virtual Display Driver Control" in the whole PC.

6. I will try the command `msiexec /l*v "install.log" /i virtual-display-driver-0.2.5-x86_64.msi`, and paste the log soon.

**Comment by MolotovCherry** [comment]
> 1. No error during installation.
> 2. There are 3 virtual display adapters because i installed the driver for 3 times.
> 3. The path `C:\Program Files\VirtualDisplayDriver` does not exist.
> 4. No shortcut or folder named or related to Virtual Display Driver.
> 5. There is no any shortcut or file named "Virtual Display Driver Control" in the whole PC.
> 6. I will try the command `msiexec /l*v "install.log" /i virtual-display-driver-0.2.5-x86_64.msi`, and paste the log soon.

Please follow the instructions [here](https://github.com/MolotovCherry/virtual-display-rs/issues/14#issuecomment-1752004214) to manually uninstall all "virtual display drivers" (though the fact that it says it's working looks right)

**Comment by xtay573269555** [comment]
1. Sorry for that there was a error during the installation i did not noticed.

<img width="384" alt="2023-10-11_09-24-57" src="https://github.com/MolotovCherry/virtual-display-rs/assets/5844466/14af1ccf-1360-4d22-ae76-f0240e10f3a7">

2. This is the detail log.
[install.log](https://github.com/MolotovCherry/virtual-display-rs/files/12863892/install.log)

**Comment by MolotovCherry** [comment]
The cause of your error is this:
> DIFXAPP: ERROR: InstallDriverPackages failed with error 0xE0000247
DIFXAPP: RETURN: InstallDriverPackages() 3758096967 (0xE0000247)

It's failing to install the driver. My best guess why this might be happening (assuming you deleted and uninstalled all those drivers first before giving me this log) is because of the certificate might not be installed correctly.

Could you also follow this suggestion about `nefconc` in [this comment](https://github.com/MolotovCherry/virtual-display-rs/issues/14#issuecomment-1752013531)? The uninstall part specifically.
`./nefconc --remove-device-node --hardware-id Root\VirtualDisplayDriver --class-guid 4d36e968-e325-11ce-bfc1-08002be10318`

I may have to start thinking of including a portable package with just the exe and driver by itself.

**Comment by MolotovCherry** [comment]
I added a portable package with just the files on their own. Before doing this, the obvious thing is, make sure everything is uninstalled, and no drivers are installed. With my original comment [here](https://github.com/MolotovCherry/virtual-display-rs/issues/14#issuecomment-1752004214), you can use pnputil to verify no more exist and delete any if they do.

You can install using the `install.reg`, add certificate (important of course), then go to device manager, click an any item in the list, go to action -> "add legacy hardware"

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/46216509-b30d-4023-b6a9-f5ec8dd907f0)

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/b0fe2639-230c-4c25-9697-710e51843df3)

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/79b5a21c-fe46-4a49-aef9-aaa2de1aa9b4)

Press Have Disk
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/05966710-72a2-4cf7-b47e-93c8d1c195d5)

And finish the process

**Comment by xtay573269555** [comment]
The last log was generated before uninstall the driver.

This log is generated after i uninstalled the driver, and i checked there is no virtual display adapter in Device Manager.

Here is my step:
1. run install-cert.bat with admin privileges in right click menu.
2. run `msiexec /l*v "install.log" /i virtual-display-driver-0.2.5-x86_64.msi` in windows terminal with admin privileges.
[new_install.log](https://github.com/MolotovCherry/virtual-display-rs/files/12864079/new_install.log)

**Comment by MolotovCherry** [comment]
> The last log was generated before uninstall the driver.
> 
> This log is generated after i uninstalled the driver, and i checked there is no virtual display adapter in Device Manager.
> 
> Here is my step:
> 
> 1. run install-cert.bat with admin privileges in right click menu.
> 2. run `msiexec /l*v "install.log" /i virtual-display-driver-0.2.5-x86_64.msi` in windows terminal with admin privileges.
>    [new_install.log](https://github.com/MolotovCherry/virtual-display-rs/files/12864079/new_install.log)

Looks like the same error. [We got a build in the queue now](https://github.com/MolotovCherry/virtual-display-rs/actions/runs/6477060524/job/17586678114). You can try the steps to manually install it above (should make things simpler)

**Comment by xtay573269555** [comment]
I can't find the `install.reg` file. Missing the download link ?

**Comment by MolotovCherry** [comment]
> I can't find the `install.reg` file. Missing the download link ?

The build is in the queue, hold on a moment. It'll be ready shortly

**Comment by xtay573269555** [comment]
It seems that the cert was not imported successfully.

I run the command and get the output:
```
PS C:\Users\zfr\Desktop\virtual-display-driver-x64> certutil -addstore -f root "DriverCertificate.cer"
root "Trusted Root Certification Authorities"
Signature matches Public Key
Certificate "DriverCertificate" added to store.
CertUtil: -addstore command completed successfully.
PS C:\Users\zfr\Desktop\virtual-display-driver-x64> certutil -addstore -f TrustedPublisher "DriverCertificate.cer"
TrustedPublisher "Trusted Publishers"
Signature matches Public Key
Related Certificates:

Exact match:
Element 6:
Serial Number: 0dee6d126821b7456b9f248f3d9b2a
Issuer: CN=DriverCertificate
 NotBefore: 9/14/2023 12:24 AM
 NotAfter: 1/1/2040 7:59 AM
Subject: CN=DriverCertificate
Signature matches Public Key
Root Certificate: Subject matches Issuer
Cert Hash(sha1): 5dfa7e68997ed52d4b10420407860d1c29b6f427

Certificate "DriverCertificate" already in store.
CertUtil: -addstore command completed successfully.
```

The second command says 'Certificate "DriverCertificate" already in store' because i double click to import the cert file to TrustedPublisher before i run the command.

**Comment by xtay573269555** [comment]
> I added a portable package with just the files on their own. Before doing this, the obvious thing is, make sure everything is uninstalled, and no drivers are installed. With my original comment [here](https://github.com/MolotovCherry/virtual-display-rs/issues/14#issuecomment-1752004214), you can use pnputil to verify no more exist and delete any if they do.
> 
> (All that remains is for the package to actually be built) Edit: Build is in the queue now
> 
> You can install using the `install.reg`, add certificate (important of course), then go to device manager, click an any item in the list, go to action -> "add legacy hardware"
> 
> ![image](https://user-images.githubusercontent.com/13651622/274118194-46216509-b30d-4023-b6a9-f5ec8dd907f0.png)
> 
> Install hardware that I manually select from a list
> 
> ![image](https://user-images.githubusercontent.com/13651622/274118241-b0fe2639-230c-4c25-9697-710e51843df3.png)
> 
> Next on show all devices
> 
> ![image](https://user-images.githubusercontent.com/13651622/274118261-79b5a21c-fe46-4a49-aef9-aaa2de1aa9b4.png)
> 
> Press Have Disk and select the folder containing the driver ![image](https://user-images.githubusercontent.com/13651622/274118302-05966710-72a2-4cf7-b47e-93c8d1c195d5.png)
> 
> And finish the process

It works. The devices is normal in device manager. Thanks a lot.

**Comment by MolotovCherry** [comment]
Glad to hear it! Enjoy!
