### ISSUE TITLE
Unable to install driver using device manager

### ISSUE THREAD

**Issue by fr1g** [MolotovCherry/virtual-display-rs#205]
Tried as #49 said but in the very end of wizard it said `Not installed, having 1 Error` or sth else.
Meanwhile, seems the installer version was installed nothing.

**Comment by fr1g** [comment]
WELL DONE, ISSUE TEMPLATE YOU MADE.

**Comment by MolotovCherry** [comment]
I take it you solved the problem, or you asked/will ask in one of the suggested places?

**Comment by fr1g** [comment]
unsolved, annoyed, tiredMaybe I’ll come back later and try to fill your issue template. 发自我的 iPhone在 2024年11月10日，01:02，Cherry ***@***.***> 写道：﻿
I take it you solved the problem, or you asked/will ask in one of the suggested places?

**Comment by MolotovCherry** [comment]
Feel free to open a discussion thread on this repo (discussion section) or post in my discord server. Discord will be the fastest way for you to get help.

I also edited my last comment with the instructions in case you weren't able to see that yet
