### ISSUE TITLE
Rework gui control app

### ISSUE THREAD

**Issue by sajjadG** [MolotovCherry/virtual-display-rs#23]
I'm getting this error on a windows 11 VM installed in hyper-v on windows 11.
![Screenshot from 2023-10-21 15-34-02](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/d54b1949-57b9-49d0-8d35-b1b9737b50d1)

trying to use this virual display to increase the resolution of this VM created via [easy-gpu-pv](https://github.com/jamesstringerparsec/Easy-GPU-PV) script.

**Comment by MolotovCherry** [comment]
I really couldn't say what's wrong in your VM, but opengl is pretty standard for any device which has gpu support. I'd check that your gpu support/drivers are properly functioning.

**Comment by sajjadG** [comment]
Oh sorry. I just remembered about Hyper-V GPU-P not working fine with OpenGL. It's been created to work good with directx. They've mentioned it in [their notes](https://github.com/jamesstringerparsec/Easy-GPU-PV#notes): 

> Vulkan renderer is unavailable and GL games may or may not work. [This](https://www.microsoft.com/en-us/p/opencl-and-opengl-compatibility-pack/9nqpsl29bfff?SilentAuth=1&wa=wsignin1.0#activetab=pivot:overviewtab) may help with some OpenGL apps.

GPU-P is a way to partition your graphic card into smaller parts using hyper-v technology. So this bug is not related to your app directly. probably egui guys can fix it not using opengl in windows but that's something they have to decide.

Thanks for your fast response <3
Cheers

**Comment by MolotovCherry** [comment]
I see! As a side note to this, I'd prefer my control app not to require opengl in the first place, though that'd require finding a better solution.

**Comment by MolotovCherry** [comment]
Due to the state of ui libraries, I don't see any real option for the quick forseeable future. I'll keep this on my mind for now, but it may be a very long time - if I ever rewrite it.

How does a cli sound though?

**Comment by updawg** [comment]
Yeah I have the same issue. I had to install the monitor through hyper-v
directly and then couldn't touch the app again when connecting through
parsec. So a CLI option would be great.

**Comment by MolotovCherry** [comment]
For those of you with this error, can you do something for me?

In your vm or whatever that doesn't support opengl, how does this website look and perform to you?
https://www.egui.rs/

**Comment by updawg** [comment]
Looks fine to me: https://imgur.com/a/r2B1BEU

This is from a hyper-v VM connected via parsec

**Comment by MolotovCherry** [comment]
Windows native app is in the works, which will solve all these problems, plus look much better.

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/9c9f60d8-b780-47b8-80d3-1a0ec17f43f5)

**Comment by updawg** [comment]
Thank you! Looking forward to this!

**Comment by sajjadG** [comment]
> Windows native app is in the works, which will solve all these problems, plus look much better.
> 
> ![image](https://user-images.githubusercontent.com/13651622/281914418-9c9f60d8-b780-47b8-80d3-1a0ec17f43f5.png)

when will this be released?

**Comment by sajjadG** [comment]
Good work @MolotovCherry <3

**Comment by the-epoch** [comment]
I have this same error on a physical machine (not a VM) that is headless (ie. no monitors attached).
From the text in the error, this appears to be a problem with the path - "c:\Users\runneradmin\... " definitely does not exist in m,y build.
This path seems to be hard coded somewhere.
![2023-11-23 155546 virtualdisplayrs error](https://github.com/MolotovCherry/virtual-display-rs/assets/46307734/d9f293d2-e671-4698-b107-eecc52efba61)

**Comment by MolotovCherry** [comment]
@the-epoch This is a fault of the graphics driver on the system, or something to do with Windows. If your system is headless, that may be why. Opengl is pretty standard for any system which uses graphics to support.

I am making a different gui app for this which does not require opengl, but for now, there is no way to solve that unless you can solve the underlying issue in your drivers/os.
