### ISSUE TITLE
Limit each frame ms time on WaitForSingleObject

### ISSUE THREAD

**Issue by MolotovCherry** [MolotovCherry/virtual-display-rs#3]
Currently hard coded to 16ms, which is fine for 60hz. We should share the monitor's refresh rate over and wait for the maximum of 1 frame for the refresh rate. Not a big deal right now, but could be a good optimization

It's not clear whether making such a change would result in any actual performance improvements, so this issue remains open until a resolution is found.

So far seems to be fine without any change

**Comment by TsuZing** [comment]
Is this the reason for performance decline? I'm streaming game on 120Hz virtual display, game's fps doesn't reach 120fps and unstable. Keep game running and press Win+shift+← to switch game to physical display, game can stable at 120fps.

**Comment by MolotovCherry** [comment]
> Is this the reason for performance decline? I'm streaming game on 120Hz virtual display, game's fps doesn't reach 120fps and unstable. Keep game running and press Win+shift+← to switch game to physical display, game can stable at 120fps.

No, I highly doubt it.
