### ISSUE TITLE
The app don't start again - Oh no :( (0x80070002)

### ISSUE THREAD

**Issue by LawMontagut** [MolotovCherry/virtual-display-rs#41]
I use the app one time yesterday, today I try to start again and I only have this. I try to restart and install all again but nothing.
![Captura de pantalla 2023-11-22 013239](https://github.com/MolotovCherry/virtual-display-rs/assets/57510795/847a4a32-f550-4f28-9dfd-72da2cae8b86)
Please, help!

**Comment by MolotovCherry** [comment]
Open device manager and check the status of the driver. The app can't connect to it because it's not running. Probably you just need to disable/enable the driver.

**Comment by LawMontagut** [comment]
Thank you so much!
