### ISSUE TITLE
[Feature Request] Add DOS Commands to Control the Virtual Display

### ISSUE THREAD

**Issue by KingOfGitH** [MolotovCherry/virtual-display-rs#43]
Thank you for this project, I am using this project for Sunshine streaming.

I currently have two monitors, Display 1 and Virtual Display 2. I have configured the system to display only on Virtual Display 2. However, after the system goes to sleep and I try to use streaming again, I encounter a prompt indicating no video output. This requires me to manually log in to the RDP desktop and switch the virtual display. 

Therefore, I hope to have a few DOS commands for a batch file to perform the display switch before login. Thank you.

**Comment by JLCareglio** [comment]
I am also using Sunshine streaming and would like a utility to manage virtual monitors compatible with commands.

👀 any news? how did you solve it?
thanks in advance 👍
