### ISSUE TITLE
Virtual Monitor as tablet display 

### ISSUE THREAD

**Issue by Marocco2** [MolotovCherry/virtual-display-rs#52]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this request has not already been filed

## Description

**Is your feature request related to a problem? Please describe.**
I use virtual-display-rs in conjunction with Sunshine and Moonlight client. I have a desktop PC as host and a Surface Pro as client. I'd like to use most of touch related features on Windows (basic ones are already there) but other features like Windows Ink or optimized tablet menu bar don't show up.

**Describe the solution you'd like**
Register a virtual monitor as it comes from a tablet PC with digitalizer

**Describe alternatives you've considered**
Pretty much it's my only option asking support here

**Additional context**
None

**Comment by MolotovCherry** [comment]
This is beyond the scope of this project, considering this is only meant to be a virtual display driver. Acting/registering as a touch screen device serves no real purpose within the scope of what the driver is designed to do.

To the best of my current knowledge, this would require making a separate driver anyways.

**Comment by Marocco2** [comment]
> This is beyond the scope of this project, considering this is only meant to be a virtual display driver. Acting/registering as a touch screen device serves no real purpose within the scope of a non-physical display.
> 
> To the best of my current knowledge, this would require making a separate driver (hence, an entirely new project).
> 
> 

That's really unfortunate but thanks anyway

**Comment by MolotovCherry** [comment]
It's a shame that Win11 had to make it so difficult! It was possible on Win10 at least
