### ISSUE TITLE
Add common modelines more easily

### ISSUE THREAD

**Issue by xieve** [MolotovCherry/virtual-display-rs#90]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this request has not already been filed

## Description

**Is your feature request related to a problem? Please describe.**
I am using Sunshine & Moonlight to stream from my desktop to my laptop and my phone. These [two](https://github.com/Nonary/ResolutionAutomation) [scripts](https://github.com/Nonary/MonitorSwapAutomation) enable me to have a near seamless experience together with virtual-display-rs, provided the resolution of my client corresponds with one of the resolutions I have set. If not, I need to find out what the resolution of my client is and set it. Ideally, I'd be able to set a resolution in Moonlight and if it were not completely uncommon, it would be set on my desktop before connecting. I could also set half the resolution to conserve power and bandwidth.

**Describe the solution you'd like**
If there was an option to just add most modelines to my virtual monitor with one click, that would be great.

**Describe alternatives you've considered**
Theoretically, the script author might integrate with virtual-display-rs more tightly and set the resolutions directly. That would be most ideal, but given the simplistic nature of the project, I believe that's rather unrealistic. 

Obviously, I can just add all the modelines myself, this is not a huge inconvenience to me, but it is one. Alternatively, a list of common modelines to choose from would also be practical. It could have an "add all" button, maybe.

**Comment by MolotovCherry** [comment]
I plan to make scripting support for this (e.g. with python), would that help out a bit with freedom?

**Comment by xieve** [comment]
Yes, that'd be cool. Maybe just a simple CLI wrapper around your core logic? Like
```bash
VirtualDisplayDriverControl.exe --add 1920x1080x60
VirtualDisplayDriverControl.exe --remove 1920x1080x60
```
I can see other how other remote desktop solutions could utilize this quite easily, too.

**Comment by MolotovCherry** [comment]
If what you wanted was a cli wrapper, there's already one in master, see here:
https://github.com/MolotovCherry/virtual-display-rs/discussions/60

Both cli and scripting support will be available

**Comment by MolotovCherry** [comment]
@xieve Python bindings are finished and stable now if you want to [try them out](https://github.com/MolotovCherry/virtual-display-rs/discussions/60).

**Comment by MolotovCherry** [comment]
I'm going to close this as it seems to be solved by both the python bindings and existing cli. There's an issue report which has a link to updated builds if you want to try it out.

Feel free to comment back onto this issue report if you have any more thoughts/concerns. Thanks!
